version: "3.9"
services:
  postgres:
    container_name: Questionator-Postgres-Dev
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432


  redis:
    container_name: Questionator-Redis-Dev
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_volume:
  redis_volume: